// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzspnpoqwmbqeowznkvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6c3BucG9xd21icWVvd3pua3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODE4NzcsImV4cCI6MjA2NzA1Nzg3N30.zGZfND9nRXZF1vOTi-DbXyfyo-6X9MAe4l8ExA1xmDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});